# Basic statistics
.statistics.basic:
  # Covariance
  Covariance:
    labels:
      - undirected
      - linear
      - signed
      - multivariate
      - contemporaneous
    dependencies:
    configs:
      - estimator: EmpiricalCovariance
      - estimator: EllipticEnvelope
      - estimator: GraphicalLasso
      - estimator: GraphicalLassoCV
      - estimator: LedoitWolf
      - estimator: MinCovDet
      - estimator: OAS
      - estimator: ShrunkCovariance
      - estimator: EmpiricalCovariance
        squared: True
      - estimator: EllipticEnvelope
        squared: True
      - estimator: GraphicalLasso
        squared: True
      - estimator: GraphicalLassoCV
        squared: True
      - estimator: LedoitWolf
        squared: True
      - estimator: MinCovDet
        squared: True
      - estimator: OAS
        squared: True
      - estimator: ShrunkCovariance
        squared: True

  # Precision
  Precision:
    labels:
      - undirected
      - linear
      - signed
      - multivariate
      - contemporaneous
    dependencies:
    configs:
      - estimator: EmpiricalCovariance
      - estimator: EllipticEnvelope
      - estimator: GraphicalLasso
      - estimator: GraphicalLassoCV
      - estimator: LedoitWolf
      - estimator: MinCovDet
      - estimator: OAS
      - estimator: ShrunkCovariance
      - estimator: EmpiricalCovariance
        squared: True
      - estimator: EllipticEnvelope
        squared: True
      - estimator: GraphicalLasso
        squared: True
      - estimator: GraphicalLassoCV
        squared: True
      - estimator: LedoitWolf
        squared: True
      - estimator: MinCovDet
        squared: True
      - estimator: OAS
        squared: True
      - estimator: ShrunkCovariance
        squared: True

  # Spearman's correlation coefficient
  SpearmanR:
    labels:
      - undirected
      - nonlinear
      - signed
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - squared: True
      - squared: False

  # Kendall's rank correlation coefficient
  KendallTau:
    labels:
      - undirected
      - nonlinear
      - signed
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - squared: True
      - squared: False

  # statistics based on cross-correlation (squared means we square the xcorr, not the output)
  CrossCorrelation:
    labels:
      - undirected
      - linear
      - signed/unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - statistic: "max"

      - statistic: "max"
        squared: True

      - statistic: "mean"

      - statistic: "mean"
        squared: True

      - statistic: "mean"
        sigonly: False

      - statistic: "mean"
        squared: True
        sigonly: False

.statistics.distance:
  PairwiseDistance:
    labels:
      - unsigned
      - unordered
      - nonlinear
      - undirected
    dependencies:
    configs:
      - metric: "euclidean"
      - metric: "cityblock"
      - metric: "cosine"
      - metric: "chebyshev"
      - metric: "canberra"
      - metric: "braycurtis"

  # Distance correlation
  DistanceCorrelation:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - biased: False
      - biased: True

  # Multi-scale graph correlation
  MultiscaleGraphCorrelation:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies:
    configs:

  # Hilbert-Schmidt independence criterion
  HilbertSchmidtIndependenceCriterion:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - biased: False
      - biased: True

  # # Heller-Heller-Gorfine (HHG) test
  # HellerHellerGorfine:
  #   labels:
  #     - undirected
  #     - nonlinear
  #     - unsigned
  #     - bivariate
  #     - contemporaneous
  #   dependencies:
  #   configs:

  # # Multi-scale graph correlation for time series
  # CrossMultiscaleGraphCorrelation:
  #   labels:
  #     - undirected
  #     - nonlinear
  #     - unsigned
  #     - bivariate
  #     - time-dependent
  #   dependencies:
  #   configs:
  #     - max_lag: 1
  #     - max_lag: 10

  # Distance correlation for time series
  CrossDistanceCorrelation:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - max_lag: 1
      - max_lag: 10

  DynamicTimeWarping:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - global_constraint: null
      - global_constraint: itakura
      - global_constraint: sakoe_chiba

  SoftDynamicTimeWarping:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - global_constraint: null
      - global_constraint: itakura
      - global_constraint: sakoe_chiba

  LongestCommonSubsequence:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - global_constraint: null
      - global_constraint: itakura
      - global_constraint: sakoe_chiba


  # Gromov-Wasserstain Distance
  GromovWasserstainTau:
    labels:
      - unsigned
      - distance
      - unordered
      - nonlinear
      - undirected
    dependencies:
    configs:

.statistics.causal:

  # Conditional distribution similarity statistic
  ConditionalDistributionSimilarity:
    labels:
      - directed
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies:
    configs:

  # Regression error-based causal inference
  RegressionErrorCausalInference:
    labels:
      - directed
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies:
    configs:

  # Information-geometric conditional independence
  InformationGeometricConditionalIndependence:
    labels:
      - directed
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies:
    configs:


# statistics that analyse in the frequency-domain (see Schoegl and Supp, 2006)
.statistics.spectral:
  CoherencePhase:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  CoherenceMagnitude:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  # Coherence (ordinal or squared? imaginary components of the coherence)
  ImaginaryCoherence:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  PhaseSlopeIndex:
    labels:
      - directed
      - linear/nonlinear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fmin: 0
        fmax: 0.5

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

  PhaseLockingValue:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  PhaseLagIndex:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  WeightedPhaseLagIndex:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  DebiasedSquaredPhaseLagIndex:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max


  PairwisePhaseConsistency:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max


# statistics that analyse in the wavelet-domain (only Mortlet wavelet's at the moment)
.statistics.wavelet:
  PhaseSlopeIndex:
    labels:
      - undirected
      - unsigned
      - time/frequency dependent
      - bivariate
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fmin: 0
        fmax: 0.5
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

.statistics.misc:
  LinearModel:
    labels:
      - directed
      - linear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - model: Ridge
      - model: Lasso
      - model: SGDRegressor
      - model: ElasticNet
      - model: BayesianRidge


  # Cointegration
  Cointegration:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - method: johansen
        statistic: max_eig_stat
        det_order: 0 # Constant trend
        k_ar_diff: 10

      - method: johansen
        statistic: trace_stat
        det_order: 0
        k_ar_diff: 10

      - method: johansen
        statistic: max_eig_stat
        det_order: 0 # Constant trend
        k_ar_diff: 1

      - method: johansen
        statistic: trace_stat
        det_order: 0
        k_ar_diff: 1

      - method: johansen
        statistic: max_eig_stat
        det_order: 1 # Linear trend
        k_ar_diff: 10

      - method: johansen
        statistic: trace_stat
        det_order: 1
        k_ar_diff: 10

      - method: johansen
        statistic: max_eig_stat
        det_order: 1
        k_ar_diff: 1

      - method: johansen
        statistic: trace_stat
        det_order: 1
        k_ar_diff: 1

      - method: aeg
        statistic: tstat
        autolag: aic
        maxlag: 10
        trend: c

      - method: aeg
        statistic: tstat
        autolag: aic
        maxlag: 10
        trend: ct

      - method: aeg
        statistic: tstat
        autolag: bic
        maxlag: 10
        trend: ct

  # Power envelope correlation
  PowerEnvelopeCorrelation:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - orth: False
        log: False
        absolute: False

      - orth: True
        log: False
        absolute: False

      - orth: False
        log: True
        absolute: False

      - orth: True
        log: True
        absolute: False

      - orth: True
        log: False
        absolute: True

      - orth: True
        log: True
        absolute: True
